# Generated by Django 5.0.6 on 2024-07-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_user_follow_user_following"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="follow",
            new_name="followers",
        ),
    ]
