# Generated by Django 5.0.7 on 2024-07-19 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0007_follower"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follower",
            name="follows_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers_u",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="follower",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_u",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
