# Generated by Django 5.0.7 on 2024-07-19 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0008_alter_follower_follows_user_alter_follower_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="followers",
        ),
        migrations.RemoveField(
            model_name="user",
            name="following",
        ),
    ]
