# Generated by Django 5.0.7 on 2024-07-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0009_remove_user_followers_remove_user_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="follower",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
