# Generated by Django 5.0.7 on 2024-07-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0010_follower_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="dislikes",
            field=models.IntegerField(default=0),
        ),
    ]
