# Generated by Django 5.0.7 on 2024-07-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0011_post_dislikes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="dislikes",
        ),
    ]
